
.BANK BANK_LV_MARIO_OG SLOT 1
.ORGA $4000
.SECTION "InitLevelPal" FORCE
 
 InitLevelPal:
   .INCLUDE "./includes/common/init_pals.s" NAMESPACE "MarioOG"

	INCLEVEL 11 og MarioOG
	INCLEVEL 12 og MarioOG
	INCLEVEL 13 og MarioOG
	INCLEVEL 21 og MarioOG
	INCLEVEL 22 og MarioOG
	INCLEVEL 23 og MarioOG
	INCLEVEL 31 og MarioOG
	INCLEVEL 32 og MarioOG
	INCLEVEL 33 og MarioOG
	INCLEVEL 41 og MarioOG
	INCLEVEL 42 og MarioOG
	INCLEVEL 43 og MarioOG Skypop M
.ENDS



.BANK BANK_LV_MARIO_OG SLOT 1
.SECTION "MidLevel Pals" FREE
	INCMIDLEVEL 11 og 1
	INCMIDLEVEL 12 og 1
	INCMIDLEVEL 13 og 1
	INCMIDLEVEL 21 og 0
	INCMIDLEVEL 21 og 1
	INCMIDLEVEL 21 og 2
	INCMIDLEVEL 22 og 0
	INCMIDLEVEL 22 og 1
	INCMIDLEVEL 23 og 1
	INCMIDLEVEL 31 og 1
	INCMIDLEVEL 31 og 2
	INCMIDLEVEL 32 og 1
	INCMIDLEVEL 32 og 2
	INCMIDLEVEL 32 og 3
	INCMIDLEVEL 33 og 1
	INCMIDLEVEL 41 og 1
	INCMIDLEVEL 42 og 1
	INCMIDLEVEL 42 og 2
	INCMIDLEVEL 43 og 1
	INCMIDLEVEL 43 og 2
	INCMIDLEVEL 43 og 3
	INCMIDLEVEL 43 og 4
	INCMIDLEVEL 43 og 5
	INCMIDLEVEL 43 og 6
	INCMIDLEVEL 43 og 7
.ENDS
